# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Build the application
COPY . .
RUN npm run build

# Set environment variables for MySQL. These will be overridden via command line or docker-compose as needed.
ENV MYSQL_HOST=localhost \
    MYSQL_PORT=3306 \
    MYSQL_USER=root \
    MYSQL_PASSWORD=secret \
    MYSQL_DATABASE=

EXPOSE 3000

# Start the MCP server
CMD ["node", "./build/index.js"]
